error: include the scgi request id in error messages
This should make it easier to associate log messages with particular
connection (and therefore a request log file).

Signed-off-by: Josef 'Jeff' Sipek <jeffpc@josefsipek.net>