error: make it clear that assertions don't return
This has two benefits...

(1) asserts in the default case in switch statements will no longer warn
    about potentially uninitialized variables

(2) it shaves off over 5kB of instructions

   text	   data	    bss	    dec	    hex	filename
  97854	   5712	   3337	 106903	  1a197	blahg-post
 102871	   5712	   3337	 111920	  1b530	blahg-pre