error: make it clear that assertions don't return
This has two benefits...

(1) asserts in the default case in switch statements will no longer warn
    about potentially uninitialized variables

(2) it shaves off almost 4kB of instructions

   text	   data	    bss	    dec	    hex	filename
 103706	   5592	   3337	 112635	  1b7fb	blahg-post
 107555	   5592	   3337	 116484	  1c704	blahg-pre