error: don't rely on macro redefinition doing the right thing
Instead of hoping that the sys/debug.h ASSERT & VERIFY definitions are ignored,
explicitly #undef them.

Found by sparse.

Signed-off-by: Josef 'Jeff' Sipek <jeffpc@josefsipek.net>